"use client";

import { useState } from 'react';
import {
  Card,
  CardContent,
  CardHeader,
  CardTitle,
  CardDescription,
} from '@/components/ui/card';
import {
  Accordion,
  AccordionContent,
  AccordionItem,
  AccordionTrigger,
} from '@/components/ui/accordion';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Textarea } from '@/components/ui/textarea';
import { Label } from '@/components/ui/label';
import { useToast } from '@/hooks/use-toast';

export default function SupportPage() {
  const { toast } = useToast();
  const [subject, setSubject] = useState('');
  const [description, setDescription] = useState('');

  const handleSubmitTicket = () => {
    if (!subject || !description) {
        toast({
            title: 'Incomplete Form',
            description: 'Please fill out both the subject and description fields.',
            variant: 'destructive',
        });
        return;
    }
    toast({
      title: 'Ticket Submitted',
      description:
        "We've received your request and will get back to you shortly.",
    });
    // Clear the form fields
    setSubject('');
    setDescription('');
  };

  return (
    <div className="space-y-6">
      <h1 className="text-3xl font-bold tracking-tight">
        Support & Help Center
      </h1>
      <div className="grid gap-6 md:grid-cols-2">
        <Card>
          <CardHeader>
            <CardTitle>Frequently Asked Questions</CardTitle>
            <CardDescription>
              Find answers to common questions about the Suraksha Drishti
              platform.
            </CardDescription>
          </CardHeader>
          <CardContent>
            <Accordion type="single" collapsible className="w-full">
              <AccordionItem value="item-1">
                <AccordionTrigger>How do I reset my password?</AccordionTrigger>
                <AccordionContent>
                  You can reset your password by clicking the "Forgot your
                  password?" link on the login page. An email will be sent to
                  your registered address with further instructions.
                </AccordionContent>
              </AccordionItem>
              <AccordionItem value="item-2">
                <AccordionTrigger>
                  What does an "AI Anomaly" alert mean?
                </AccordionTrigger>
                <AccordionContent>
                  An "AI Anomaly" alert is generated by our system when it
                  detects unusual patterns in a tourist's location data, such as
                  sudden deviations from a planned route, prolonged inactivity,
                  or entering a high-risk zone.
                </AccordionContent>
              </AccordionItem>
              <AccordionItem value="item-3">
                <AccordionTrigger>
                  How is the map's traffic layer updated?
                </AccordionTrigger>
                <AccordionContent>
                  The traffic layer uses real-time data from Google Maps. It is
                  updated automatically to reflect current traffic conditions.
                  You can toggle this layer on or off in the Map Settings.
                </AccordionContent>
              </AccordionItem>
              <AccordionItem value="item-4">
                <AccordionTrigger>
                  Can I view a tourist's complete location history?
                </AccordionTrigger>
                <AccordionContent>
                  For privacy reasons, the system only displays the most recent
                  location data relevant to an active alert or for general
                  monitoring. Access to full historical data is restricted and
                  requires special authorization.
                </AccordionContent>
              </AccordionItem>
            </Accordion>
          </CardContent>
        </Card>
        <Card>
          <CardHeader>
            <CardTitle>Contact Support</CardTitle>
            <CardDescription>
              If you can't find an answer, please reach out to our support team.
            </CardDescription>
          </CardHeader>
          <CardContent className="space-y-4">
            <div className="space-y-2">
              <Label htmlFor="subject">Subject</Label>
              <Input
                id="subject"
                placeholder="e.g., Issue with dispatching a unit"
                value={subject}
                onChange={(e) => setSubject(e.target.value)}
              />
            </div>
            <div className="space-y-2">
              <Label htmlFor="description">Description</Label>
              <Textarea
                id="description"
                placeholder="Please describe the issue in detail..."
                rows={5}
                value={description}
                onChange={(e) => setDescription(e.target.value)}
              />
            </div>
            <Button className="w-full" onClick={handleSubmitTicket}>
              Submit Ticket
            </Button>
          </CardContent>
        </Card>
      </div>
    </div>
  );
}
